### ISSUE TITLE
Plus UI V2.6.3 Premium Blogger Theme

### ISSUE THREAD

**Issue by s2gh** [SamirPaul1/assets#1]
[https://drive.google.com/file/d/1IsU9FknJa5YUv3FFfreDOzwzcBGRI8se/view?usp=sharing](https://drive.google.com/file/d/1IsU9FknJa5YUv3FFfreDOzwzcBGRI8se/view?usp=sharing)

`/blogger/plus-ui/plus-ui-v2.6.3.xml`

**Comment by SamirPaulb** [comment]
added. https://github.com/SamirPaul1/assets/blob/main/blogger/plus-ui/plus-ui-v2.6.3.xml
